---
title: Rollback Tweaks
description: Rollback tweaks for those who are applying from previous versions of the playbook
privilege: TrustedInstaller
onUpgrade: true
actions:

  - !writeStatus: {status: "Removing Outdated Changes"}

  - !registryValue: { path: 'HKLM\SYSTEM\ControlSet001\Control\Session Manager', value: 'HeapDeCommitFreeBlockThreshold', type: REG_DWORD, data: '0' }

  - !registryValue: { path: 'HKCU\SOFTWARE\Policies\Microsoft\Internet Explorer\Security', value: 'DisableSecuritySettingsCheck', operation: delete }
  - !registryValue: { path: 'HKLM\SOFTWARE\Policies\Microsoft\Internet Explorer\Security', value: 'DisableSecuritySettingsCheck', operation: delete }
  - !registryValue: { path: 'HKCU\SOFTWARE\Policies\Microsoft\Internet Explorer\Security', value: 'DisableFixSecuritySettings', operation: delete }
  - !registryValue: { path: 'HKLM\SOFTWARE\Policies\Microsoft\Internet Explorer\Security', value: 'DisableFixSecuritySettings', operation: delete }
  - !registryValue: { path: 'HKLM\SOFTWARE\Policies\Microsoft\Internet Explorer\Download', value: 'CheckExeSignatures', operation: delete }
  - !registryValue: { path: 'HKCU\SOFTWARE\Policies\Microsoft\Internet Explorer\Privacy', value: 'ClearBrowsingHistoryOnExit', operation: delete }
  - !registryValue: { path: 'HKLM\SOFTWARE\Policies\Microsoft\Internet Explorer\Privacy', value: 'ClearBrowsingHistoryOnExit', operation: delete }
  
  # https://github.com/meetrevision/playbook/issues/27
  - !run: {exe: 'netsh', args: 'int tcp set supplemental internet congestionprovider=default', showOutput: false, showError: false}

  # https://github.com/meetrevision/playbook/pull/31
  - !registryValue: { path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'RegisteredOrganisation', operation: delete }

  # Previously used as detection purpose
  - !registryValue: {path: 'HKLM\Software\Classes\CLSID', value: 'IsModernRCEnabled', operation: delete}

  # Breaks XboxGipSvc - https://github.com/meetrevision/playbook/issues/34
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control', value: 'SvcHostSplitThresholdInKB', type: REG_DWORD, data: '3670016'}

  # Breaks Efficiency Mode in Task Manager
  - !service: {name: 'bam', operation: change, startup: 1}

  #  The Start Recording button on GameBar is gray outed - #74
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\GameDVR', value: 'AppCaptureEnabled', operation: delete}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR', value: 'AppCaptureEnabled', operation: delete, option: '!remove-appx-xbox'}

  # Revert services
  - !service: {name: 'Beep', operation: change, startup: 1} 
  - !service: {name: 'GraphicsPerfSvc', operation: change, startup: 3}
  - !service: {name: 'Ndu', operation: change, startup: 2}

  # Setting it to 0 breaks THE FINALS
  - !registryValue:
    path: 'HKLM\SYSTEM\ControlSet001\Control\CI\Config'
    value: 'VulnerableDriverBlocklistEnable'
    type: REG_DWORD
    data: '1'

  # Revert mitigation tweaks
  - !registryKey: 
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions'
    operation: delete
  - !registryKey: 
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions'
    operation: delete
    
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\Session Manager\Memory Management', value: 'FeatureSettings', operation: delete}
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\Session Manager\Memory Management', value: 'FeatureSettingsOverride', operation: delete}
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\Session Manager\Memory Management', value: 'FeatureSettingsOverrideMask', operation: delete}

  # Automatic Maintenance
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance', value: 'MaintenanceDisabled', operation: delete, option: '!disable-automatic-maintenance'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\ScheduledDiagnostics', value: 'EnabledExecution', operation: delete, option: '!disable-automatic-maintenance'}

  # Breaks 'Your Phone'
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent', value: 'DisableWindowsConsumerFeatures', operation: delete}

  # Revert Windows Updates policies
  - !registryKey: {path: 'HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate', operation: delete}

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Servicing', value: 'RepairContentServerSource', operation: delete}
  
  # Breaks 'defrag c: -b'
  - !powerShell:
    command: |
      $path = ${env:ProgramFiles(x86)} + '\Revision Tool\data\flutter_assets\additionals\EnableSF.bat'
      Start-Process -FilePath $path -Wait -NoNewWindow

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Dfrg\BootOptimizeFunction', value: 'Enable', operation: delete}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OptimalLayout', value: 'EnableAutoLayout', operation: delete}

  # Speech Recognition
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\InputPersonalization', value: 'AllowInputPersonalization', operation: delete}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Speech_OneCore\Preferences', value: 'ModelDownloadAllowed', operation: delete}

  # OneDrive workaround
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\OneDrive', value: 'DisableFileSyncNGSC', operation: delete}

  # We manually disable all the things that RestrictCommunication does (except DisableRootAutoUpdate and AllowWindowsEntitlementReactivation, DisableWindowsUpdateAccess)
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\InternetManagement', value: 'RestrictCommunication', operation: delete}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\InternetManagement', value: 'RestrictCommunication', operation: delete}

  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\SystemCertificates\AuthRoot', value: 'DisableRootAutoUpdate', operation: delete} # Needed for MS Store to work. (31/07/2020)
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform', value: 'AllowWindowsEntitlementReactivation', operation: delete}

  # Revert Windows Defender Antivirus - Security Intelligence Updates policies
  - !registryKey: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', operation: delete}
  
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'DisableScheduledSignatureUpdateOnBattery', type: REG_DWORD, data: '1'}

  # Default Auto Tray behavior
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer', value: 'EnableAutoTray', operation: delete}

  # Allow users to log on using biometrics
  - !registryKey: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Biometrics', operation: delete}

  # Fix KGL mismatch in Xbox Game Bar
  # Disabling background apps breaks Xbox Game Bar KGL update. We remove bloat apps anyway and it can be toggled in Revision Tool
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\AppPrivacy', value: 'LetAppsRunInBackground', operation: delete}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Search', value: 'BackgroundAppGlobalToggle', operation: delete}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Search', value: 'BackgroundAppGlobalToggle', operation: delete}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications', value: 'GlobalUserDisabled', operation: delete}
  - !appx: {operation: clearCache, name: '*XboxGamingOverlay*'}


  # Internet Explorer
  - !registryKey: {path: 'HKCU\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings', operation: delete}
  - !registryKey: {path: 'HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings', operation: delete}

  - !registryKey: {path: 'HKCU\Software\Policies\Microsoft\Internet Explorer', operation: delete}
  - !registryKey: {path: 'HKLM\Software\Policies\Microsoft\Internet Explorer', operation: delete}


  
  