---
title: Initialization
description: Copies Revision folders/files, and configures some initial settings
privilege: TrustedInstaller
actions:
  
  - !writeStatus: {status: "Initializing"}

  # Prevent annoying notifications during deployment
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance'
    value: 'Enabled'
    type: REG_DWORD
    data: '0'

  - !cmd:
    exeDir: true
    command: 'robocopy "Licenses" "%SystemDrive%\Licenses" /E /PURGE /IM /IT /NP'
    ignoreErrors: true
    weight: 30
    
  - !cmd:
    exeDir: true
    command: 'copy /y "hosts" "%WINDIR%\System32\drivers\etc\hosts"'
    weight: 20

  # Necessary to clean DNS Cache after modifying hosts
  - !cmd:
    command: 'ipconfig /flushdns'

  # Wakelock modification isn't available in AME Wizard, therefore activating a custom high performance powerplan before we proceed to prevent sleep 
  - !writeStatus: {status: "Configuring a power plan"}
  - !run: {exe: "powercfg", args: "/hibernate off"}
  # https://github.com/meetrevision/playbook/issues/105
  # - !run: {exe: "powercfg", args: "-restoredefaultschemes"}
  # Delete existing Revision power plan if it exists
  - !powerShell:
    command: |
      $scheme = powercfg -getactivescheme
      if ($scheme -like '*3ff9831b-6f80-4830-8178-736cd4229e7b*') {
        powercfg -s 381b4222-f694-41f0-9685-ff5bb260df2e
        if ($LASTEXITCODE -ne 0) {
        powercfg -restoreindividualdefaultscheme 381b4222-f694-41f0-9685-ff5bb260df2e
        }
        powercfg -s 381b4222-f694-41f0-9685-ff5bb260df2e
      }
      powercfg -delete 3ff9831b-6f80-4830-8178-736cd4229e7b

  - !run: {exe: "powercfg", args: "-duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 3ff9831b-6f80-4830-8178-736cd4229e7b"}
  - !run: {exe: "powercfg", args: "-changename 3ff9831b-6f80-4830-8178-736cd4229e7b \"Revision - Ultra Performance\" \"Windows's Ultimate Performance with additional changes.\""}
  - !run: {exe: "powercfg", args: "-s 3ff9831b-6f80-4830-8178-736cd4229e7b"}
  - !run: {exe: "powercfg", args: "-setacvalueindex scheme_current sub_processor PERFINCPOL 2"}
  - !run: {exe: "powercfg", args: "-setacvalueindex scheme_current sub_processor PERFDECPOL 1"}
  - !run: {exe: "powercfg", args: "-setacvalueindex scheme_current sub_processor PERFINCTHRESHOLD 10"}
  - !run: {exe: "powercfg", args: "-setacvalueindex scheme_current sub_processor PERFDECTHRESHOLD 8"}
  - !run: {exe: "powercfg", args: "-setacvalueindex scheme_current sub_processor CPMINCORES 100"}
  - !run: {exe: "powercfg", args: "-setacvalueindex scheme_current sub_processor CPMINCORES1 100"} # on hybrid CPUs, '1' at the end of the setting name is for P-cores
  - !run: {exe: "powercfg", args: "/setactive scheme_current"}

  - !writeStatus: {status: 'Installing Revision Tool'}
  - !powerShell: {command: "& { Invoke-WebRequest ((Invoke-RestMethod -Uri 'https://api.github.com/repos/meetrevision/revision-tool/releases/latest' -Method Get | ConvertTo-Json | ConvertFrom-Json).assets | where-object { $_.name -eq 'RevisionTool-Setup.exe' }).browser_download_url -OutFile \"$env:TEMP\\RevisionTool-Setup.exe\" }", errorAction: Halt, wait: true}
  - !cmd: {command: 'call "%temp%\RevisionTool-Setup.exe" /VERYSILENT /TASKS="desktopicon"', errorAction: Halt, wait: true, weight: 150}

  - !writeStatus: {status: "Optimizing PowerShell"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File ngen.ps1'
    weight: 100