---
title: APPX
description: Removal of APPX packages
privilege: TrustedInstaller
actions:
  
  - !writeStatus: {status: "Removing Appx Packages"}
  - !powerShell:
    # runas: currentUserElevated
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 48
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.Windows.SecureAssessmentBrowser',
        'Microsoft.Windows.PeopleExperienceHost',
        'Microsoft.WindowsCamera',
        'MicrosoftWindows.Client.WebExperience',
        'Microsoft.WidgetsPlatformRuntime',
        'Microsoft.WindowsAlarms',
        'Microsoft.WindowsMaps',
        'Microsoft.MicrosoftStickyNotes',
        'microsoft.windowscommunicationsapps',
        'Microsoft.People',
        'Microsoft.BingNews',
        'Microsoft.BingSearch',
        'Microsoft.BingWeather',
        'Microsoft.MicrosoftSolitaireCollection',
        'Microsoft.WindowsFeedbackHub',
        'Microsoft.GetHelp',
        'Microsoft.Getstarted',
        'Microsoft.Todos',
        'Microsoft.PowerAutomateDesktop',
        'Microsoft.549981C3F5F10', # Cortana
        'MicrosoftCorporationII.QuickAssist',
        'MicrosoftCorporationII.MicrosoftFamily',
        'Microsoft.ZuneMusic',
        'Microsoft.ZuneVideo',
        'Microsoft.WindowsSoundRecorder',
        'Clipchamp.Clipchamp',
        'Microsoft.Whiteboard',
        'Microsoft.MicrosoftTeamsforSurfaceHub',
        'MicrosoftCorporationII.MailforSurfaceHub',
        'Microsoft.MicrosoftPowerBIForWindows',
        'Microsoft.SkypeApp',
        'Microsoft.MicrosoftOfficeHub',
        'Microsoft.Office.Excel',
        'Microsoft.Office.PowerPoint',
        'Microsoft.Office.Word',
        'Microsoft.Office.OneNote',
        'Microsoft.OutlookForWindows',
        'SpotifyAB.SpotifyMusic',
        'OutlookPWA',
        'Flipgrid',
        'Microsoft.Microsoft3DViewer',
        'Microsoft.Advertising',
        'MixedReality.Portal',
        'Microsoft.MSPaint', # Paint 3D
        'MicrosoftTeams',
        'MSTeams', # New Teams
        'Microsoft.StartExperiencesApp'
      )

  - !writeStatus: {status: "Removing Photos"}
  - !powerShell:
    option: "remove-appx-photos"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'Microsoft.Windows.Photos'

  - !writeStatus: {status: "Removing Dev Home", option: "remove-appx-devhome"}
  - !powerShell:
    option: "remove-appx-devhome"
    # runas: currentUserElevated
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'Microsoft.Windows.DevHome'
    
  - !writeStatus: {status: "Removing Xbox Apps", option: "remove-appx-xbox"}
  - !powerShell:
    option: "remove-appx-xbox"
    # runas: currentUserElevated
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.Xbox',
        'Microsoft.XboxApp', # Xbox Console Companion is deprecated
        'Microsoft.GamingApp',
        'Microsoft.XboxGameCallableUI'
      )
  - !appx: {name: 'Microsoft.XboxGameCallableUI*', type: family, weight: 10, option: "remove-appx-xbox"}

    #139
  - !registryValue: {path: 'HKCR\ms-gamebar', value: '', type: REG_SZ, data: 'URL:ms-gamebar', option: "remove-appx-xbox"}
  - !registryValue: {path: 'HKCR\ms-gamebar', value: 'URL Protocol', type: REG_SZ, data: '', option: "remove-appx-xbox"}
  - !registryKey: {path: 'HKCR\ms-gamebar\shell\open\command', operation: add, option: "remove-appx-xbox"}
  - !registryValue: {path: 'HKCR\ms-gamebar', value: '', type: REG_SZ, data: '%SystemRoot%\System32\systray.exe', option: "remove-appx-xbox"}
  - !registryValue: {path: 'HKCU\Software\Microsoft\GameBar', value: 'ShowStartupPanel', type: REG_DWORD, data: '0', option: "remove-appx-xbox"}

  - !writeStatus: {status: "Removing Your Phone", option: "remove-appx-yourphone"}
  - !powerShell:
    option: "remove-appx-yourphone"
    # runas: currentUserElevated
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 20
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.YourPhone',
        'MicrosoftWindows.CrossDevice'
      )

  - !writeStatus: {status: "Removing Recall", option: "remove-appx-recall"}
  - !powerShell:
    option: "remove-appx-recall"
    # runas: currentUserElevated
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'MicrosoftWindows.Client.AIX'
  
#   - !writeStatus: {status: "Removing Appx Packages"}
#   # - !appx: {name: '*Disney*', type: family, weight: 10}

#   - !appx: {name: '*microsoft.microsoftedge.stable*', type: family, errorAction: Ignore, weight: 10, option: "remove-edge"}
#   - !appx: {name: '*Microsoft.MicrosoftEdge*', type: family, errorAction: Ignore, weight: 10, option: "remove-edge"}
#   - !appx: {name: '*Microsoft.MicrosoftEdgeDevToolsClient*', errorAction: Ignore, type: family, weight: 10, option: "remove-edge"}
#   - !file: {path: "C:\\Windows\\SystemApps\\Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe", errorAction: Ignore, option: "remove-edge"}
#   - !appx: {name: 'Microsoft.Copilot*', type: family, errorAction: Ignore, weight: 10, option: "remove-edge"}

#   - !writeStatus: {status: "Removing OneDrive"}
#   - !appx: {name: '*OneDrive*', type: family, errorAction: Ignore, weight: 10, option: "remove-onedrive"}

#   - !writeStatus: {status: "Removing Spotify"}
#   - !appx: {name: '*Spotify*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing SecureAssessmentBrowser"}
#   - !appx: {name: '*SecureAssessmentBrowser*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing PeopleExperienceHost"}
#   - !appx: {name: '*PeopleExperienceHost*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing Photos"}
#   - !appx: {name: '*Microsoft.Windows.Photos*', type: family, option: "remove-appx-photos", weight: 10}
#   - !writeStatus: {status: "Removing Camera"}
#   - !appx: {name: '*Microsoft.WindowsCamera*', type: family, weight: 10}
  
#   - !writeStatus: {status: "Removing Widgets"}
#   - !powerShell:
#     command: 'Get-AppxPackage MicrosoftWindows.Client.WebExperience | Remove-AppxPackage'
#     runas: currentUserElevated
#   - !appx: {name: '*MicrosoftWindows.Client.WebExperience*', errorAction: Ignore, type: family, weight: 10}

#   - !writeStatus: {status: "Removing Alarms"}
#   - !appx: {name: '*Microsoft.WindowsAlarms*', type: family, weight: 10}
 
#   - !writeStatus: {status: "Removing Maps"}
#   - !appx: {name: '*Microsoft.WindowsMaps*', type: family, weight: 10}
  
#   - !writeStatus: {status: "Removing Sticky Notes"}
#   - !appx: {name: '*Microsoft.MicrosoftStickyNotes*', type: family, weight: 10}
  
#   - !writeStatus: {status: "Removing Mail"}
#   - !powerShell:
#     command: 'Get-AppxPackage *windowscommunicationsapps* | Remove-AppxPackage'
#     runas: currentUserElevated
#   - !appx: {name: '*microsoft.windowscommunicationsapps*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing People"}
#   - !appx: {name: '*Microsoft.People*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing BingNews"}
#   - !appx: {name: '*Microsoft.BingNews*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing BingSearch"}
#   - !appx: {name: '*BingSearch*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing BingWeather"}
#   - !appx: {name: '*Microsoft.BingWeather*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing Solitaire"}
#   - !appx: {name: '*Microsoft.MicrosoftSolitaireCollection*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing Feedback"}
#   - !appx: {name: '*Microsoft.WindowsFeedbackHub*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing GetHelp"}
#   - !appx: {name: '*Microsoft.GetHelp*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing GetStarted"}
#   - !appx: {name: '*Microsoft.Getstarted*', type: family, weight: 10}
#     # Get Started placeholder
#   # - !appx: {name: '*WebExperienceHost*', type: app, unregister: true, weight: 10}

#   - !writeStatus: {status: "Removing Todos"}
#   - !appx: {name: '*Microsoft.Todos*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing PowerAutomate"}
#   - !appx: {name: '*Microsoft.PowerAutomateDesktop*', type: family, weight: 10}
#     # Cortana
#   - !writeStatus: {status: "Removing Cortana"}
#   - !appx: {name: '*Microsoft.549981C3F5F10*', type: family, weight: 10}
  
#   - !writeStatus: {status: "Removing QuickAssist"}
#   - !appx: {name: '*MicrosoftCorporationII.QuickAssist*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing MS Family"}
#   - !appx: {name: '*MicrosoftCorporationII.MicrosoftFamily*', type: family, weight: 10}
  
#   - !writeStatus: {status: "Removing ZuneMusic"}
#   - !appx: {name: '*Microsoft.ZuneMusic*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing ZuneVideo"}
#   - !appx: {name: '*Microsoft.ZuneVideo*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing SoundRecorder"}
#   - !appx: {name: '*Microsoft.WindowsSoundRecorder*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing Clipchamp"}
#   - !appx: {name: '*Clipchamp.Clipchamp*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing Whiteboard"}
#   - !appx: {name: '*Microsoft.Whiteboard*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing skydrive"}
#   - !appx: {name: '*microsoft.microsoftskydrive*', type: family, weight: 10}
  
#   - !writeStatus: {status: "Removing TeamsforSurfaceHub"}
#   - !appx: {name: '*Microsoft.MicrosoftTeamsforSurfaceHub*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing MailforSurfaceHub"}
#   - !appx: {name: '*MicrosoftCorporationII.MailforSurfaceHub*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing PowerBI"}
#   - !appx: {name: '*Microsoft.MicrosoftPowerBIForWindows*', type: family, weight: 10}
#   - !writeStatus: {status: "Removing Skype"}
#   - !appx: {name: '*Microsoft.SkypeApp*', type: family, weight: 10}
 
#   - !writeStatus: {status: "Removing UWP Office"}
#   - !appx: {name: '*Microsoft.MicrosoftOfficeHub*', type: family, weight: 10}
#   - !appx: {name: '*Microsoft.Office.Excel*', type: family, weight: 10}
#   - !appx: {name: '*Microsoft.Office.PowerPoint*', type: family, weight: 10}
#   - !appx: {name: '*Microsoft.Office.Word*', type: family, weight: 10}
#   - !appx: {name: '*Microsoft.Office.OneNote*', type: family, weight: 10}

#   - !appx: {name: '*OutlookForWindows*', type: family, weight: 10}
#   - !appx: {name: '*OutlookPWA*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing 3DViewer"}
#   - !appx: {name: '*Microsoft.Microsoft3DViewer*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing Advertising"}
#   - !appx: {name: 'Microsoft.Advertising*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing MixedRealityPortal"}
#   - !appx: {name: '*MixedReality.Portal*', type: family, weight: 10}
  
#     # Paint 3D
#   - !writeStatus: {status: "Removing Paint 3D"}
#   - !appx: {name: '*Microsoft.MSPaint*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing Teams"}
#   - !taskKill: {name: "*teams*", errorAction: Ignore}
#   - !appx: {name: '*MicrosoftTeams*', type: family, weight: 10}
#     # new Teams
#   - !powerShell: {command: 'Get-AppxPackage *MSTeams* | Remove-AppxPackage', runas: currentUserElevated}
#   - !appx: {name: '*MSTeams*', type: family, weight: 10}

#   # Breaks Windows Updates
#   # - !writeStatus: {status: "Removing Banners"}
#     # MicrosoftWindows.Client.CBS_cw5n1h2txyewy!
#   # - !appx: {name: '*Global.ValueBanner*', type: app, unregister: true, weight: 50}
#   # - !appx: {name: '*Global.WsxPackManager*', type: app, unregister: true, weight: 50}
#   #   # MicrosoftWindows.Client.Core_cw5n1h2txyewy
#   # - !appx: {name: '*Global.BackupBanner*', type: app, unregister: true, weight: 50}

#   - !writeStatus: {status: "Removing Dev Home"}
#   - !appx: {name: '*DevHome*', type: family, option: "remove-appx-devhome", weight: 10}
  
#   # - !writeStatus: {status: "Removing Windows Backup"}
#   # - !appx: {name: '*WindowsBackup*', type: app, unregister: true, option: "remove-appx-wbackup", weight: 10}

#   - !writeStatus: {status: "Removing FlipGrid"}
#   - !appx: {name: '*Flipgrid*', type: family, weight: 10}

#   - !writeStatus: {status: "Removing Xbox Apps", option: "remove-appx-xbox"}
#   - !appx: {name: '*Microsoft.Xbox*', type: family, weight: 10, option: "remove-appx-xbox"}
#   - !appx: {name: '*Microsoft.GamingApp*', type: family, option: "remove-appx-xbox"}
#   # Xbox Console Companion is deprecated
#   - !appx: {name: '*Microsoft.XboxApp*', type: family} 

  
#   - !writeStatus: {status: "Removing Your Phone", option: "remove-appx-yourphone"}
#   - !appx: {name: '*Microsoft.YourPhone*', type: family, weight: 10, option: "remove-appx-yourphone"}
#   - !appx: {name: '*MicrosoftWindows.CrossDevice*', type: family, weight: 10, option: "remove-appx-yourphone"}

#   - !writeStatus: {status: "Removing Recall", option: "remove-appx-recall"}
#   - !appx: {name: '*MicrosoftWindows.Client.AIX*', type: family, weight: 10, option: "remove-appx-recall"}
