---
title: Configuration
description: Applies some Revision configurations
privilege: TrustedInstaller
actions:

  # Disable Memory Compression
  - !powerShell: 
    command: 'Disable-MMAgent -mc'

  # Disable Superfetch for SSDs
  # Might not work on VMs
  - !powerShell:
    command: |
      $mediaType = (Get-PhysicalDisk -SerialNumber (Get-Disk -Number (Get-Partition -DriveLetter $env:SystemDrive.Substring(0, 1)).DiskNumber).SerialNumber.TrimStart()).MediaType
      if ($mediaType -eq 'SSD') {
        $path = ${env:ProgramFiles(x86)} + '\Revision Tool\data\flutter_assets\additionals\DisableSF.bat'
        Start-Process -FilePath $path -Wait -NoNewWindow
      }
  
  - !cmd:
    command: 'setx DOTNET_CLI_TELEMETRY_OPTOUT 1'
    runas: currentUserElevated
    
  - !cmd:
    command: 'setx POWERSHELL_TELEMETRY_OPTOUT 1'
    runas: currentUserElevated

  - !writeStatus: {status: "Removing logs"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File CLEANER.ps1'
    weight: 150

  - !writeStatus: {status: "Finalizing process"}
  - !registryValue: {path: 'HKCU\System\GameConfigStore', value: 'GameDVR_FSEBehaviorMode', type: REG_DWORD, data: '0', weight: 70}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications', value: 'GlobalUserDisabled', type: REG_DWORD, data: '1', weight: 60}

  - !powerShell: {command: 'Get-ScheduledTask -TaskPath "\Microsoft\Office\*" | Disable-ScheduledTask'}

   # OneDrive workaround
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\OneDrive', value: 'DisableFileSyncNGSC', operation: delete}

  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File SVCGROUP.ps1'
    weight: 50

  - !run: {exeDir: true, exe: "FINALIZE.cmd", weight: 200}

  - !run:
    exeDir: true
    exe: "STARTMENU.cmd"
    option: "remove-pinned-items-startmenu"
    weight: 100

  - !run:
    exeDir: true
    exe: "FILEASSOC.cmd"
    option: "configure-lpv"
    weight: 150

  - !cmd:
    exeDir: true
    command: 'robocopy "Wallpapers" "%systemroot%\Web\Wallpaper\MeetRevision\v2" /E /PURGE /IM /IT /NP'
    ignoreErrors: true

  - !powerShell:
    command: '.\WALLPAPER.ps1 -Mode Desktop -ImagePath $env:systemroot\Web\Wallpaper\MeetRevision\v2\desktop.jpg'
    exeDir: true
    runas: currentUserElevated
    option: "configure-wallpaper"
    weight: 45

  - !powerShell: 
    command: '.\WALLPAPER.ps1 -Mode LockScreen -ImagePath $env:systemroot\Web\Wallpaper\MeetRevision\v2\lockscreen.jpg'
    exeDir: true
    runas: currentUserElevated
    option: "configure-wallpaper"
    weight: 45 

  - !writeStatus: {status: "Configuring features"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File DISM-FEATURES.ps1'
    weight: 270

    # Necessary to refresh start menu entries etc.
  - !appx: {operation: clearCache, name: '*Client.CBS*'}
  - !appx: {operation: clearCache, name: '*StartMenuExperienceHost*', option: "remove-pinned-items-startmenu"}
  - !appx: {operation: clearCache, name: '*Windows.Search*'}
  - !appx: {operation: clearCache, name: '*TCUI*'}
    # Workaround for KGL versions to match
  - !appx: {operation: clearCache, name: '*XboxGameCallableUI*'}
  - !appx: {operation: clearCache, name: '*XboxGameOverlay*'}
  - !appx: {operation: clearCache, name: '*XboxGamingOverlay*'}
  - !appx: {operation: clearCache, name: '*XboxIdentityProvider*'}
  - !appx: {operation: clearCache, name: '*XboxSpeechToTextOverlay*'}

    # Start as user process to prevent weird look due to running as TrustedInstaller
  # - !run: {baseDir: true, exe: "NSudoLC.exe", args: '-U:C -UseCurrentConsole explorer.exe'}