---
title: configure-explorer-settings
description: configure-explorer-settings
privilege: TrustedInstaller
actions:

    # ===============
    # === General ===
    # ===============
    # === Open File Exlporer to - This PC (instead of Quick Access)
    # [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
    # "LaunchTo"=dword:00000001
    # === Show recently used files in Quick Access - Enabled
    # [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
    # "ShowRecent"=dword:00000001
    # === Show frequently used files in Quick Access - Enabled
    # [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer]
    # "ShowFrequent"=dword:00000001
    # ============
    # === View ===
    # ============
    # === Display the full path in title bar - Enabled
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState', value: 'FullPath', type: REG_DWORD, data: '1'}
    # === Hide extensions for known file types - Disabled
    # ------> Disabled for Security reasons
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'HideFileExt', type: REG_DWORD, data: '0'}
    # === Show sync provider notifications (ads) - Disabled
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowSyncProviderNotifications', type: REG_DWORD, data: '0'}
    # =============
    # === Extra ===
    # =============
    # === Increased context options time threshold
    # ------> If selecting and right clicking more than x amount of items, some context options disappear (i.e. Take ownership), this will increase the threshold.
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer', value: 'MultipleInvokePromptMinimum', type: REG_DWORD, data: '100'}
  - !registryValue: {path: 'HKCU\Software\Winaero.com\Winaero Tweaker\Changes', value: 'pageContextMenuSelectionLimit', type: REG_DWORD, data: '1'}
    # === Disable Wallpaper JPEG (.jpg) image Compression.
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'JPEGImportQuality', type: REG_DWORD, data: '100'}
    # === Disable system beeps.
  - !registryValue: {path: 'HKCU\Control Panel\Sound', value: 'Beep', type: REG_SZ, data: 'no'}
    # === Disable ' - Shortcut.' text on shortcut creation.
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', value: 'link', type: REG_BINARY, data: '00000000'}
    # === Always show all icons and notifications on the taskbar - Disabled
    # ------> The default for this can be set under HKEY_LOCAL_MACHINE.
    # ------> Defaulted due to removal of subjective changes.
    # [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer]
    # "EnableAutoTray"=dword:00000001
    # === Always show more details in a file copy dialog - Enabled
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager', value: 'EnthusiastMode', type: REG_DWORD, data: '1'}
    # === AutoPlay - Disabled
    # ------> Auto play is the notification that pops up when you insert an external storage device, like a USB.
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers', value: 'DisableAutoplay', type: REG_DWORD, data: '1'}
    # === AutoRun - Disabled
    # ------> Disable autorun will limit the functionality of autorun.inf on all disks.
    # ------> https://learn.microsoft.com/en-us/windows/win32/shell/autoplay-reg
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoDriveTypeAutoRun', type: REG_DWORD, data: '255'}
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoDriveTypeAutoRun', type: REG_DWORD, data: '255'}
    # === Show Task View button in taskbar - Enabled
    # ------> Defaulted due to removal of subjective changes.
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowTaskViewButton', type: REG_DWORD, data: '1'}
    # === Windows low disk space checking - Disabled
    # ------> (Also prevents idle hard disks from going into standby)
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoLowDiskSpaceChecks', type: REG_DWORD, data: '1'}
    # === Changes the time (milliseconds) it takes for the tooltips to pop up when hovering your mouse over elements to 30 ms. (default = 400 ms)
  - !registryValue: {path: 'HKCU\Control Panel\Mouse', value: 'MouseHoverTime', type: REG_SZ, data: '30'}
    # === Makes the Start Menu appear almost instantly when you click on the Windows icon in the Taskbar.
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'MenuShowDelay', type: REG_SZ, data: '0'}
    # === Specifies time (in milliseconds) that the mouse needs to remain over a window before the window is activated. (current setting is 10 ms)
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'ActiveWndTrkTimeout', type: REG_DWORD, data: '10'}
    # === Do not track Shell shortcuts during roaming - Enabled
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsExplorer::LinkResolveIgnoreLinkInfo
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'LinkResolveIgnoreLinkInfo', type: REG_DWORD, data: '1'}
    # === Do not use the search-based method when resolving shell shortcuts - Enabled
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.StartMenu::NoResolveSearch
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoResolveSearch', type: REG_DWORD, data: '1'}
    # === Do not use the tracking-based method when resolving shell shortcuts - Enabled
    # ------> Disables NTFS tracking features.
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.StartMenu::NoResolveTrack
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoResolveTrack', type: REG_DWORD, data: '1'}
    # === Disables the blue screen that pops up when you're trying to shutdown or restart, asking you to save your work.
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'AutoEndTasks', type: REG_SZ, data: '0'}
  - !registryValue: {path: 'HKU\.DEFAULT\Control Panel\Desktop', value: 'AutoEndTasks', type: REG_SZ, data: '0'}
    # === HungAppTimeout also specifies how long (5 seconds by default) the system waits for user processes to end after the user clicks/taps on the End task button in Task Manager.
    # ------> Changed 2 seconds (2000), default is 5 seconds (5000).
    # ------> https://www.tenforums.com/tutorials/97842-change-hungapptimeout-value-windows-10-a.html
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'HungAppTimeout', type: REG_SZ, data: '2000'}
  - !registryValue: {path: 'HKU\.DEFAULT\Control Panel\Desktop', value: 'HungAppTimeout', type: REG_SZ, data: '2000'}
    # === The WaitToKillAppTimeout value determines how long the system waits for user processes to end after the user attempts to sign out, restart, or shut down Windows.
    # ------> Changed to 2 seconds (2000), default is 20 seconds (20000).
    # ------> https://www.eightforums.com/threads/waittokillapptimeout-specify-for-shutdown-in-windows.37424/
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'WaitToKillAppTimeout', type: REG_SZ, data: '2000'}
  - !registryValue: {path: 'HKU\.DEFAULT\Control Panel\Desktop', value: 'WaitToKillAppTimeout', type: REG_SZ, data: '2000'}
    # === This value controls the timeout period in milliseconds for all low-level hooks.
    # ------> https://www.registryrecycler.com/blog/2013/07/speed-up-your-windows-pc-through-registry/
    # ------> https://www.quickmacros.com/au/help/api/Au.AHookWin.LowLevelHooksTimeout.html#Au_AHookWin_LowLevelHooksTimeout_remarks
    # ------> https://bit.ly/300Dqwh
  - !registryValue: {path: 'HKCU\Control Panel\Desktop', value: 'LowLevelHooksTimeout', type: REG_SZ, data: '1000'}
  - !registryValue: {path: 'HKU\.DEFAULT\Control Panel\Desktop', value: 'LowLevelHooksTimeout', type: REG_SZ, data: '1000'}
    # === Speed up shutdown time by lowering the amount of time it takes the OS to close/kill background Services.
    # ------> Changed to 1.5 seconds (1500), default is 5 seconds (5000).
    # ------> https://www.sevenforums.com/tutorials/717-shut-down-speed-up.html
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control', value: 'WaitToKillServiceTimeout', type: REG_SZ, data: '1500'}
    # === Disable Taskbar Animations. (prevents the pop up windows in the taskbar from getting stuck too)
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarAnimations', type: REG_DWORD, data: '0', option: 'configure-explorer-taskbar-animations'}
  
  - !registryValue: { path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarAnimations', operation: delete, option: '!configure-explorer-taskbar-animations' }


    # === Turn off display of recent search entries in the File Explorer search box - Enabled
    # ------> Additionally this also disables Bing in the Start Menu in Windows 10's May 2020 update (20H1).
    # ------> https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\Windows\Explorer', value: 'DisableSearchBoxSuggestions', type: REG_DWORD, data: '1'}
    
    # === Disable the new Weather and News widgets
    # ------> Other parts of it can be found in configure-ifeo
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds', value: 'EnableFeeds', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Feeds', value: 'ShellFeedsTaskbarViewMode', type: REG_DWORD, data: '2'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarDa', type: REG_DWORD, data: '0'}
    # ------> since 22621.1343 builds, Windows 11 tries to reinstall WebExperience even if it is removed and stored in deprovisioned apps list
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Dsh', value: 'AllowNewsAndInterests', type: REG_DWORD, data: '0'}

  
    # ==========================
    # === Attachment Manager ===
    # ==========================
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', value: 'SmartScreenEnabled', type: REG_SZ, data: 'Off'}
    # === Default risk level for file attachments - Disable the warning The Publisher could not be verified
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.AttachmentManager::AM_SetFileRiskLevel
    # ------> https://www.tenforums.com/antivirus-firewalls-system-security/17588-disabling-smartscreen-windows-10-does-not-actually-disable.html
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Associations', value: 'DefaultFileTypeRisk', type: REG_DWORD, data: '1808'}
    # === Do not preserve zone information in file attachments - Enabled
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments', value: 'SaveZoneInformation', type: REG_DWORD, data: '1'}
    # === Inclusion list for low file types - Enabled (list found below)
  # - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Associations', value: 'LowRiskFileTypes', type: REG_SZ, data: '.avi;.bat;.com;.cmd;.exe;.htm;.html;.lnk;.mpg;.mpeg;.mov;.mp3;.msi;.m3u;.rar;.reg;.txt;.vbs;.wav;.zip;'}
    # === Inclusion list for moderate risk file types - Enabled (list found below)
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Associations', value: 'ModRiskFileTypes', type: REG_SZ, data: '.bat;.exe;.reg;.vbs;.chm;.msi;.js;.cmd'}
    # === Notify antivirus programs when opening attachments - Disabled
    # ------> Default is 3
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments', value: 'ScanWithAntiVirus', type: REG_DWORD, data: '1'}


  # === Disables Automatic Folder Type Discovery
  # ------> Disabling it fixes the 'folder always loading' issue when a folder contains a lot of media files.  
  # ------> https://www.windowslatest.com/2024/03/04/windows-11-can-open-big-folders-in-file-explorer-faster-if-you-turn-off-folder-discovery/
  - !registryValue: {path: 'HKCU\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell', value: 'FolderType', type: REG_SZ, data: 'NotSpecified'} 

  # === Force explorer to use high performance GPU
  - !registryValue: { path: 'HKCU\Software\Microsoft\DirectX\UserGpuPreferences', value: 'C:\Windows\explorer.exe', type: REG_SZ, data: 'GpuPreference=2;' }

  # === Disable  "Include account-based insights, recent, favorite and recommended" for OneDrive in File Explorer
  - !registryValue: { path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'DisableGraphRecentItems', type: REG_DWORD, data: '1' }

  # ===  Disable Group By in the Downloads folder to avoid unnecessary dates comparison
  - !powerShell: 
    runas: trustedInstaller
    command: |
      $folderTypesKey = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderTypes'
      $downloadsFolderID = '{885a186e-a440-4ada-812b-db871b942259}'

      $path = Join-Path -Path $folderTypesKey -ChildPath $downloadsFolderID
      Get-ChildItem -Path $path -Recurse | ForEach-Object {
        if ((Get-ItemProperty -Path $_.PSPath).GroupBy) {
            Set-ItemProperty -Path $_.PSPath -Name GroupBy -Value ''
          }
      }
    
    # Necesarry to refresh 'Bags' to have an 
  - !powerShell: 
    runas: currentUserElevated
    command: |
      $downloadsFolderID = '{885a186e-a440-4ada-812b-db871b942259}'
      $bagsPath = 'HKCU:\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags'
      Get-ChildItem -Path $bagsPath | ForEach-Object {
        $fullPath = Join-Path -Path $_.PSPath -ChildPath 'Shell\{885A186E-A440-4ADA-812B-DB871B942259}'
        if (Test-Path -Path $fullPath) {
          Remove-Item -Path $fullPath -Recurse
        } 
      }


  # === Disable the new Spotlight icon on Desktop
  - !registryValue: { path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel', value: '{2cc5ca98-6485-489a-920e-b3e88a6ccce3}', type: REG_DWORD, data: '1' }

    # ========================
    # === Discarded Tweaks ===
    # ========================
    # === Remove "Give access to" from context menu.
    # ------> (Discarded due to insignificance)
    # [-HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\Directory\Background\shellex\ContextMenuHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\Directory\shellex\ContextMenuHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\Directory\shellex\CopyHookHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\Directory\shellex\PropertySheetHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\Drive\shellex\ContextMenuHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\Drive\shellex\PropertySheetHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\LibraryFolder\background\shellex\ContextMenuHandlers\Sharing]
    # [-HKEY_CLASSES_ROOT\UserLibraryFolder\shellex\ContextMenuHandlers\Sharing]
    # === Disables useless Explorer items/features.
    # ------> (Discarded due to conflictions with Quick Access and file/folder history)
    # [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
    # "Start_ShowRun"=dword:00000001
    # "Start_TrackDocs"=dword:00000000
    # "Start_JumpListItems"=dword:00000000
