---
title: Configure Explorer -> Context Menu
description: Configure the context menu in Windows Explorer
privilege: TrustedInstaller
actions:

  # Enables the classic right click context menu in Explorer on Windows 11
  - !registryValue: {path: 'HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32', value: '', type: REG_SZ, data: '', option: "configure-lcm"}

  # === Add Take Ownership to the context menu.
  - !registryKey: {path: 'HKCR\*\shell\runas'}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: '', type: REG_SZ, data: 'Take Ownership'}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: 'NoWorkingDirectory', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\*\shell\runas', value: 'Position', type: REG_SZ, data: 'middle'}
  - !registryValue: {path: 'HKCR\*\shell\runas\command', value: '', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryValue: {path: 'HKCR\*\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryKey: {path: 'HKCR\Directory\shell\runas'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: '', type: REG_SZ, data: 'Take Ownership'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'AppliesTo', type: REG_SZ, data: 'NOT (System.ItemPathDisplay:="C:\Users" OR System.ItemPathDisplay:="C:\ProgramData" OR System.ItemPathDisplay:="C:\Windows" OR System.ItemPathDisplay:="C:\Windows\System32" OR System.ItemPathDisplay:="C:\Program Files" OR System.ItemPathDisplay:="C:\Program Files (x86)")'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'NoWorkingDirectory', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\Directory\shell\runas', value: 'Position', type: REG_SZ, data: 'middle'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas\command', value: '', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" /r /d y && icacls "%1" /grant *S-1-3-4:F /t /c /l /q'}
  - !registryValue: {path: 'HKCR\Directory\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" /r /d y && icacls "%1" /grant *S-1-3-4:F /t /c /l /q'}
  - !registryKey: {path: 'HKCR\dllfile\shell\runas'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: '', type: REG_SZ, data: 'Take Ownership'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: 'NoWorkingDirectory', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas', value: 'Position', type: REG_SZ, data: 'middle'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas\command', value: '', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryValue: {path: 'HKCR\dllfile\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: 'cmd.exe /c takeown /f "%1" && icacls "%1" /grant *S-1-3-4:F /c /l'}
  - !registryKey: {path: 'HKCR\exefile\shell\runas'}
  - !registryValue: {path: 'HKCR\exefile\shell\runas', value: 'HasLUAShield', type: REG_SZ, data: ''}
  - !registryValue: {path: 'HKCR\exefile\shell\runas\command', value: '', type: REG_SZ, data: '"%1" %*'}
  - !registryValue: {path: 'HKCR\exefile\shell\runas\command', value: 'IsolatedCommand', type: REG_SZ, data: '"%1" %*'}
