---
title: Configure Explorer -> Search
description: Configure Search
privilege: TrustedInstaller
actions:

  # === (perf) Respect Power Settings when Indexing - Enabled (Win11 only)
  # ------> PC is in Battery Saver, Best Power Efficiency, or Game Mode; Process usage exceeds 80%; Disk usage goes up above 70%
  # ------> https://www.elevenforum.com/t/turn-on-or-off-respect-power-settings-when-indexing-in-windows-11.2960/
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows Search\Gather\Windows\SystemIndex', value: 'RespectPowerModes', type: REG_DWORD, data: '1'}

  # === (perf) Prevent indexing when running on battery power to conserve energy - Enabled
  # ------> https://winaero.com/disable-search-indexing-battery-windows-10/
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'PreventIndexOnBattery', type: REG_DWORD, data: '1'}

  # === Turn off display of recent search entries in the File Explorer search box - Enabled
  # ------> Additionally this also disables Bing in the Start Menu in Windows 10's May 2020 update (20H1).
  # ------> https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.WindowsExplorer::DisableSearchBoxSuggestions
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\Windows\Explorer', value: 'DisableSearchBoxSuggestions', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Policies\Microsoft\Windows\Explorer', value: 'DisableSearchBoxSuggestions', type: REG_DWORD, data: '1'}

  # === Allow Cloud Search - User Selected
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=FullArmor.Policies.3B9EA2B5_A1D1_4CD5_9EDE_75B22990BC21::AllowCloudSearch
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowCloudSearch', type: REG_DWORD, data: '2'}

  # === Allow Cortana above lock screen - Disabled
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowCortanaAboveLock', type: REG_DWORD, data: '0'}

  # === Allow Cortana - Disabled
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowCortana', type: REG_DWORD, data: '1'}

  # === Allow Cortana Page in OOBE on an AAD account - Disabled
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=FullArmor.Policies.3B9EA2B5_A1D1_4CD5_9EDE_75B22990BC21::AllowCortanaInAAD
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowCortanaInAAD', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowCortanaInAADPathOOBE', type: REG_DWORD, data: '0'}

  # === Allow search and Cortana to use location - Disabled
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'AllowSearchToUseLocation', type: REG_DWORD, data: '0'}

  # === Don't search the web or display web results in Search - Enabled
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'ConnectedSearchUseWeb', type: REG_DWORD, data: '0'}

  # === Don't search the web or display web results in Search over metered connections - Enabled
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'ConnectedSearchUseWebOverMeteredConnections', type: REG_DWORD, data: '0'}

  # === Do not allow web search - Enabled
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'DisableWebSearch', type: REG_DWORD, data: '1'}

  # === Set the SafeSearch setting for Search - Off (Disabled)
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'ConnectedSearchSafeSearch', type: REG_DWORD, data: '3'}

  # === Set what information is shared in Search - Anonymous info
  # ------> Anonymous info: Share usage information but don't share search history, Microsoft account info or specific location
  # ------> https://admx.help/?Category=Windows_11_2022&Policy=FullArmor.Policies.3B9EA2B5_A1D1_4CD5_9EDE_75B22990BC21::SearchPrivacy
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search', value: 'ConnectedSearchPrivacy', type: REG_DWORD, data: '3'}

  # === Disable Bing Integration in the Start Menu
  # ------> Only applies to 1909 and lower.
  # ------> https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Search', value: 'CortanaConsent', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Search', value: 'CortanaConsent', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Search', value: 'BingSearchEnabled', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Search', value: 'BingSearchEnabled', type: REG_DWORD, data: '0'}

  # === Automatic Update of Speech Data - Off
  # ------> https://www.howto-connect.com/enable-disable-automatic-update-speech-data-windows-10/
  # - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Speech_OneCore\Preferences', value: 'ModelDownloadAllowed', type: REG_DWORD, data: '0'}

  # === Cortana on Lock Screen - Disabled
  # ------> https://winaero.com/blog/how-to-enable-cortana-on-lock-screen/
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Speech_OneCore\Preferences', value: 'VoiceActivationEnableAboveLockscreen', type: REG_DWORD, data: '0'}